BEGIN TRANSACTION;
INSERT INTO `value` VALUES (1,'Январь','январь','04-1',NULL);
INSERT INTO `value` VALUES (2,'Февраль','февраль','04-2',NULL);
INSERT INTO `value` VALUES (3,'Март','март','04-3',NULL);
INSERT INTO `value` VALUES (4,'Апрель','апрель','04-4',NULL);
INSERT INTO `value` VALUES (5,'Май','май','04-5',NULL);
INSERT INTO `value` VALUES (6,'Июнь','июнь','04-6',NULL);
INSERT INTO `value` VALUES (7,'Июль','июль','04-7',NULL);
INSERT INTO `value` VALUES (8,'Август','август','04-8',NULL);
INSERT INTO `value` VALUES (9,'Сентябрь','сентябрь','04-9',NULL);
INSERT INTO `value` VALUES (10,'Октябрь','октябрь','04-10',NULL);
INSERT INTO `value` VALUES (11,'Ноябрь','ноябрь','04-11',NULL);
INSERT INTO `value` VALUES (12,'Декабрь','декабрь','04-12',NULL);
INSERT INTO `value` VALUES (13,'2007','2007','2007',NULL);
INSERT INTO `value` VALUES (14,'2008','2008','2008',NULL);
INSERT INTO `value` VALUES (15,'2009','2009','2009',NULL);
INSERT INTO `value` VALUES (16,'2010','2010','2010',NULL);
INSERT INTO `value` VALUES (17,'2011','2011','2011',NULL);
INSERT INTO `value` VALUES (18,'2012','2012','2012',NULL);
INSERT INTO `value` VALUES (19,'2013','2013','2013',NULL);
INSERT INTO `value` VALUES (20,'2014','2014','2014',NULL);
INSERT INTO `value` VALUES (21,'2015','2015','2015',NULL);
INSERT INTO `value` VALUES (22,'2016','2016','2016',NULL);
INSERT INTO `value` VALUES (23,'Внешний долг','внешний долг','33-1',NULL);
INSERT INTO `value` VALUES (24,'Задолженность странам, вошедшим в Парижский клуб','задолженность страна войти парижский клуб','33-20',NULL);
INSERT INTO `value` VALUES (25,'Задолженность странам, не вошедшим в Парижский клуб','задолженность страна не войти парижский клуб','33-2',NULL);
INSERT INTO `value` VALUES (26,'Задолженность бывшим странам СЭВ','задолженность бывший страна сэв','33-3',NULL);
INSERT INTO `value` VALUES (27,'Задолженность бывшего СССР','задолженность бывший ссср','33-21',NULL);
INSERT INTO `value` VALUES (28,'Задолженность перед международными финансовыми организациями','задолженность международный финансовый организация','33-4',NULL);
INSERT INTO `value` VALUES (29,'Еврооблигационные займы','еврооблигационный заём','33-5',NULL);
INSERT INTO `value` VALUES (30,'Облигации внутреннего государственного валютного займа','облигация внутренний государственный валютный заём','33-6',NULL);
INSERT INTO `value` VALUES (31,'Иные','иной','33-7',NULL);
INSERT INTO `value` VALUES (32,'Предоставление гарантий Российской Федерации в иностранной валюте','предоставление гарантия российский федерация иностранный валюта','33-8',NULL);
INSERT INTO `value` VALUES (33,'Внутренний долг','внутренний долг','33-9',NULL);
INSERT INTO `value` VALUES (34,'Государственные гарантии Российской Федерации','государственный гарантия российский федерация','33-10',NULL);
INSERT INTO `value` VALUES (35,'Государственные ценные бумаги Российской Федерации','государственный ценный бумага российский федерация','33-11',NULL);
INSERT INTO `value` VALUES (36,'Облигации федерального займа (с переменным купонным доходом','облигация федеральный заём переменный купонный доход','33-12',NULL);
INSERT INTO `value` VALUES (37,'Облигации федерального займа (с постоянным доходом','облигация федеральный заём постоянный доход','33-13',NULL);
INSERT INTO `value` VALUES (38,'Облигаций федерального займа с индексируемым номиналом','облигация федеральный заём индексировать номинал','33-14',NULL);
INSERT INTO `value` VALUES (39,'Облигации федерального займа (с амортизацией дохода','облигация федеральный заём амортизация доход','33-15',NULL);
INSERT INTO `value` VALUES (40,'Государственные сберегательные облигации с постоянной процентной','государственный сберегательный облигация постоянный процентный','33-16',NULL);
INSERT INTO `value` VALUES (41,'Облигации с фиксированной процентной ставкой купонного дохода','облигация фиксировать процентный ставка купонный доход','33-17',NULL);
INSERT INTO `value` VALUES (42,'Облигации внутренних облигационных займов','облигация внутренний облигационный заём','33-18',NULL);
INSERT INTO `value` VALUES (43,'БОФЗ','бофз','33-19',NULL);
INSERT INTO `measure` VALUES (1,'Значение','значение','VALUE');
INSERT INTO `measure` VALUES (2,'Доля в структуре','доля структура','VALDIVPARENT');
INSERT INTO `dimension_value` VALUES (1,1);
INSERT INTO `dimension_value` VALUES (2,1);
INSERT INTO `dimension_value` VALUES (3,1);
INSERT INTO `dimension_value` VALUES (4,1);
INSERT INTO `dimension_value` VALUES (5,1);
INSERT INTO `dimension_value` VALUES (6,1);
INSERT INTO `dimension_value` VALUES (7,1);
INSERT INTO `dimension_value` VALUES (8,1);
INSERT INTO `dimension_value` VALUES (9,1);
INSERT INTO `dimension_value` VALUES (10,1);
INSERT INTO `dimension_value` VALUES (11,1);
INSERT INTO `dimension_value` VALUES (12,1);
INSERT INTO `dimension_value` VALUES (13,2);
INSERT INTO `dimension_value` VALUES (14,2);
INSERT INTO `dimension_value` VALUES (15,2);
INSERT INTO `dimension_value` VALUES (16,2);
INSERT INTO `dimension_value` VALUES (17,2);
INSERT INTO `dimension_value` VALUES (18,2);
INSERT INTO `dimension_value` VALUES (19,2);
INSERT INTO `dimension_value` VALUES (20,2);
INSERT INTO `dimension_value` VALUES (21,2);
INSERT INTO `dimension_value` VALUES (22,2);
INSERT INTO `dimension_value` VALUES (23,3);
INSERT INTO `dimension_value` VALUES (24,3);
INSERT INTO `dimension_value` VALUES (25,3);
INSERT INTO `dimension_value` VALUES (26,3);
INSERT INTO `dimension_value` VALUES (27,3);
INSERT INTO `dimension_value` VALUES (28,3);
INSERT INTO `dimension_value` VALUES (29,3);
INSERT INTO `dimension_value` VALUES (30,3);
INSERT INTO `dimension_value` VALUES (31,3);
INSERT INTO `dimension_value` VALUES (32,3);
INSERT INTO `dimension_value` VALUES (33,3);
INSERT INTO `dimension_value` VALUES (34,3);
INSERT INTO `dimension_value` VALUES (35,3);
INSERT INTO `dimension_value` VALUES (36,3);
INSERT INTO `dimension_value` VALUES (37,3);
INSERT INTO `dimension_value` VALUES (38,3);
INSERT INTO `dimension_value` VALUES (39,3);
INSERT INTO `dimension_value` VALUES (40,3);
INSERT INTO `dimension_value` VALUES (41,3);
INSERT INTO `dimension_value` VALUES (42,3);
INSERT INTO `dimension_value` VALUES (43,3);
INSERT INTO `dimension` VALUES (1,'Months');
INSERT INTO `dimension` VALUES (2,'Years');
INSERT INTO `dimension` VALUES (3,'Marks');
INSERT INTO `cube_measure` VALUES (1,1);
INSERT INTO `cube_measure` VALUES (2,1);
INSERT INTO `cube_dimension` VALUES (1,1);
INSERT INTO `cube_dimension` VALUES (2,1);
INSERT INTO `cube_dimension` VALUES (3,1);
INSERT INTO `cube` VALUES (1,'CLMR02','Госдолг','долг госдолг облигация заём задолженность федеральный доход обязательства гарантия ценный бумага');
COMMIT;
